
# Travis CI Configuration file
# @link https://travis-ci.org/

language: java
sudo: false
#install: true
#addons:
  #sonarqube:
    #organization: "61a949c5fe3c61472319c424345c409c78ffc0bc"
    #token:
      #secure: "your_token_encrypted_with_travis_encrypt_tool"
jdk:
  - oraclejdk8
matrix:
  include:
    - jdk: oraclejdk8
      env: DEPLOY=true

script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  script:
   - mvn clean dependency:list test install -U
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'